services:
  - docker

jobs:
  include:
    - stage: build
      script:
      - docker build -t twitteranalytics .
      - docker images

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN