language: csharp

mono: none
sudo: required
dist: xenial
dotnet: 2.2

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_script:
    - sudo apt -y install nuget
    - nuget install OpenCover -ExcludeVersion -source "https://api.nuget.org/v3/index.json"

script:
    - dotnet restore
    - dotnet build TwitterAnalytics.sln -c Release
    - dotnet test -c Release TwitterAnalytics.BusinessLogic.UnitTests/TwitterAnalytics.BusinessLogic.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=80


after_script:
        - bash <(curl -s https://codecov.io/bash)