language: csharp

mono: 5.12.0
sudo: required
dist: xenial
dotnet: 2.2

env:
    global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
    - dotnet restore
    - dotnet build TwitterAnalytics.sln -c Release
    - dotnet test -c Release TwitterAnalytics.BusinessLogic.UnitTests/TwitterAnalytics.BusinessLogic.UnitTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=80

after_script:
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - ./codecov -f "*opencover.xml"