language: csharp

mono: none
sudo: required
dist: xenial
dotnet: 2.2

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_script:
    - dotnet add package OpenCover --version 4.6.519

script:
    - dotnet restore
    - dotnet build TwitterAnalytics.sln -c Release
    - dotnet test -c Release  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover 
    - ./OpenCover.4.6.519/tools/OpenCover.Console.exe -target:"dotnet" -targetargs:"test .\TwitterAnalytics.BusinessLogic.UnitTests/TwitterAnalytics.BusinessLogic.UnitTests.csproj --no-build -c Release /p:codecov=true" /p:Threshold=80 -register:user -oldstyle -safemode:off -returntargetcode -output:coverage.xml 

after_script:
        - bash <(curl -s https://codecov.io/bash)